// Mock data for development when Supabase is not configured

export const mockCategories = [
  { id: '4', name: 'Home Decor', slug: 'home-decor', description: 'Cushions, pillows, decorations and household items', display_order: 1 },
  { id: '1', name: 'Bags', slug: 'bags', description: 'Tote bags, crossbody bags, and more', display_order: 2 },
  { id: '3', name: 'Accessories', slug: 'accessories', description: 'Pouches, wallets, and small items', display_order: 3 },
  { id: '2', name: 'Other', slug: 'other', description: 'Other sewing patterns and projects', display_order: 4 },
]

export const mockPatterns = [
  {
    id: '1',
    slug: 'classic-tote-bag',
    title: 'Classic Tote Bag Pattern',
    description: 'A versatile tote bag perfect for everyday use. Includes multiple pockets and sturdy handles.',
    long_description: '<h2>About This Pattern</h2><p>This <strong>classic tote bag pattern</strong> is perfect for beginners and experienced sewists alike. The pattern includes detailed instructions for creating a spacious bag with interior pockets, reinforced handles, and a professional finish.</p><p><em>Great for shopping, beach trips, or everyday use.</em></p><h3>Features</h3><ul><li>Spacious main compartment</li><li>Interior pockets for organization</li><li>Reinforced handles for durability</li><li>Professional finish techniques</li></ul>',
    price: 12.99,
    category: 'bags',
    cover_url: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800',
    preview_images: [
      'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=400',
      'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400',
    ],
    file_url: '/patterns/classic-tote-bag.pdf',
    difficulty: 'beginner' as const,
    tags: ['bag', 'tote', 'beginner'],
    whats_included: [
      'Full-size pattern pieces',
      'Step-by-step instructions with diagrams',
      'Fabric requirements list',
      'Assembly guide',
    ],
    tools_needed: [
      'Sewing machine',
      'Fabric scissors',
      'Paper scissors',
      'Ruler',
      'Pins',
      'Iron',
      'Seam ripper',
    ],
    materials_needed: [
      'Sewing thread (100% polyester, same color as fabric)',
      'Main fabric (1 yard cotton or canvas)',
      'Lining fabric (1 yard)',
      'Interfacing (optional, for extra structure)',
    ],
    featured: true,
    bestseller: true,
    active: true,
    rating_avg: 4.8,
    rating_count: 124,
    sales_count: 2100,
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
    categories: { name: 'Bags', slug: 'bags' },
  },
  {
    id: '2',
    slug: 'crossbody-bag-pattern',
    title: 'Crossbody Bag with Adjustable Strap',
    description: 'Stylish crossbody bag with adjustable strap and zipper closure.',
    long_description: '<h2>About This Pattern</h2><p>Create your own <strong>fashionable crossbody bag</strong> with this intermediate-level pattern. Features include an adjustable strap, secure zipper closure, and multiple compartments for organization.</p><h3>Key Features</h3><ul><li>Adjustable shoulder strap</li><li>Secure zipper closure</li><li>Multiple interior compartments</li><li>Professional finish</li></ul><p><em>Perfect for everyday use or special occasions!</em></p>',
    price: 14.99,
    category: 'bags',
    sale_type: 'percentage',
    sale_value: 25,
    cover_url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800',
    preview_images: [],
    file_url: '/patterns/crossbody-bag.pdf',
    difficulty: 'intermediate' as const,
    tags: ['bag', 'crossbody', 'zipper'],
    whats_included: [
      'Full-size pattern pieces',
      'Detailed zipper installation guide',
      'Strap adjustment tutorial',
      'Finishing techniques',
    ],
    tools_needed: [
      'Sewing machine',
      'Zipper foot',
      'Fabric scissors',
      'Ruler',
      'Pins',
      'Iron',
      'Seam ripper',
    ],
    materials_needed: [
      'Sewing thread (100% polyester)',
      'Main fabric (1.5 yards)',
      'Lining fabric (1 yard)',
      'Zipper (9 inch)',
      'Webbing for strap (2 yards)',
      'Interfacing',
    ],
    featured: true,
    bestseller: false,
    active: true,
    rating_avg: 4.9,
    rating_count: 89,
    sales_count: 542,
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2024-02-01T00:00:00Z',
    categories: { name: 'Bags', slug: 'bags' },
  },
  {
    id: '3',
    slug: 'simple-apron-pattern',
    title: 'Simple Kitchen Apron',
    description: 'Easy-to-make apron perfect for beginners. Great for kitchen or crafting.',
    long_description: '<h2>Perfect First Project</h2><p>This <strong>beginner-friendly apron pattern</strong> is perfect for your first sewing project. Simple construction with adjustable neck strap and waist ties.</p><h3>What You\'ll Make</h3><ul><li>Adjustable neck strap</li><li>Long waist ties</li><li>Two front pockets</li><li>Professional hemming</li></ul><p><em>Great for kitchen or crafting!</em></p>',
    price: 8.99,
    cover_url: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?w=800',
    preview_images: [],
    file_url: '/patterns/simple-apron.pdf',
    difficulty: 'beginner' as const,
    category: 'other',
    tags: ['apron', 'kitchen', 'beginner'],
    whats_included: [
      'Full-size pattern',
      'Beginner-friendly instructions',
      'Pocket placement guide',
      'Tie construction tutorial',
    ],
    tools_needed: [
      'Sewing machine',
      'Fabric scissors',
      'Ruler',
      'Pins',
      'Iron',
      'Measuring tape',
    ],
    materials_needed: [
      'Sewing thread (matching color)',
      'Main fabric (2 yards cotton or linen)',
      'Bias tape for neck strap (optional)',
    ],
    featured: false,
    bestseller: true,
    active: true,
    rating_avg: 4.7,
    rating_count: 156,
    sales_count: 1024,
    created_at: '2024-01-20T00:00:00Z',
    updated_at: '2024-01-20T00:00:00Z',
    categories: { name: 'Other', slug: 'other' },
  },
  {
    id: '4',
    slug: 'zipper-pouch-set',
    title: 'Zipper Pouch Set (3 Sizes)',
    description: 'Versatile zipper pouches in small, medium, and large sizes.',
    long_description: '<h2>Three Sizes, Endless Possibilities</h2><p>Learn to make <strong>professional zipper pouches</strong> with this comprehensive pattern. Includes three sizes perfect for makeup, pencils, or travel essentials.</p><h3>Included Sizes</h3><ul><li>Small: 5" x 7" (makeup, coins)</li><li>Medium: 7" x 9" (pencils, toiletries)</li><li>Large: 9" x 12" (tablets, documents)</li></ul><p><em>Great for gifts or personal use!</em></p>',
    price: 11.99,
    cover_url: 'https://images.unsplash.com/photo-1564584217132-2271feaeb3c5?w=800',
    preview_images: [],
    file_url: '/patterns/zipper-pouch.pdf',
    difficulty: 'intermediate' as const,
    category: 'accessories',
    tags: ['pouch', 'zipper', 'accessories'],
    whats_included: [
      'Patterns for 3 sizes',
      'Zipper installation guide',
      'Lining techniques',
      'Finishing tips',
    ],
    tools_needed: [
      'Sewing machine',
      'Zipper foot',
      'Fabric scissors',
      'Ruler',
      'Pins',
      'Iron',
    ],
    materials_needed: [
      'Sewing thread',
      'Outer fabric (1 yard)',
      'Lining fabric (1 yard)',
      'Zippers (7", 9", 12")',
      'Interfacing (optional)',
    ],
    featured: false,
    bestseller: false,
    active: true,
    rating_avg: 4.6,
    rating_count: 78,
    sales_count: 432,
    created_at: '2024-02-10T00:00:00Z',
    updated_at: '2024-02-10T00:00:00Z',
    categories: { name: 'Accessories', slug: 'accessories' },
  },
  {
    id: '5',
    slug: 'cushion-cover-pattern',
    title: 'Envelope Cushion Cover',
    description: 'Easy envelope-style cushion cover with no zipper required.',
    long_description: '<h2>No Zipper Needed!</h2><p>Create <strong>beautiful cushion covers</strong> with this simple envelope-back design. Perfect for refreshing your home decor without the hassle of zippers.</p><h3>Available Sizes</h3><ul><li>12" x 12" (small)</li><li>16" x 16" (standard)</li><li>20" x 20" (large)</li><li>12" x 20" (lumbar)</li></ul><p><em>Quick project, beautiful results!</em></p>',
    price: 9.99,
    cover_url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
    preview_images: [],
    file_url: '/patterns/cushion-cover.pdf',
    difficulty: 'beginner' as const,
    category: 'home-decor',
    tags: ['cushion', 'home decor', 'beginner'],
    whats_included: [
      'Multiple size options',
      'Envelope back tutorial',
      'Fabric calculation guide',
      'Finishing techniques',
    ],
    tools_needed: [
      'Sewing machine',
      'Fabric scissors',
      'Ruler',
      'Pins',
      'Iron',
      'Measuring tape',
    ],
    materials_needed: [
      'Sewing thread',
      'Home decor fabric (varies by size)',
      'Cushion insert',
    ],
    featured: false,
    bestseller: false,
    active: true,
    rating_avg: 4.5,
    rating_count: 92,
    sales_count: 618,
    created_at: '2024-01-25T00:00:00Z',
    updated_at: '2024-01-25T00:00:00Z',
    categories: { name: 'Home Decor', slug: 'home-decor' },
  },
  {
    id: '6',
    slug: 'bucket-bag-pattern',
    title: 'Modern Bucket Bag',
    description: 'Trendy bucket bag with drawstring closure and shoulder strap.',
    long_description: '<h2>Stylish & Functional</h2><p>This <strong>modern bucket bag pattern</strong> is perfect for intermediate sewists looking for a stylish project. Features a drawstring closure, adjustable shoulder strap, and interior pocket.</p><h3>Design Features</h3><ul><li>Drawstring closure</li><li>Adjustable shoulder strap</li><li>Interior zippered pocket</li><li>Structured base</li><li>Professional hardware</li></ul><p><em>Make a statement with this trendy bag!</em></p>',
    price: 15.99,
    sale_type: 'amount',
    sale_value: 4,
    cover_url: 'https://images.unsplash.com/photo-1590739225017-e0d0f3e4e8c2?w=800',
    preview_images: [],
    file_url: '/patterns/bucket-bag.pdf',
    difficulty: 'advanced' as const,
    category: 'bags',
    tags: ['bag', 'bucket bag', 'advanced'],
    whats_included: [
      'Full-size pattern pieces',
      'Drawstring construction guide',
      'Strap making tutorial',
      'Professional finishing techniques',
    ],
    tools_needed: [
      'Sewing machine',
      'Heavy-duty needle',
      'Fabric scissors',
      'Ruler',
      'Pins',
      'Iron',
      'Eyelet setter',
    ],
    materials_needed: [
      'Sewing thread (heavy-duty)',
      'Main fabric (2 yards canvas or faux leather)',
      'Lining fabric (1.5 yards)',
      'Interfacing (stiff)',
      'Drawstring cord (2 yards)',
      'D-rings and hardware',
      'Zipper (7 inch for pocket)',
    ],
    featured: true,
    bestseller: false,
    active: true,
    rating_avg: 4.9,
    rating_count: 45,
    sales_count: 287,
    created_at: '2024-02-15T00:00:00Z',
    updated_at: '2024-02-15T00:00:00Z',
    categories: { name: 'Bags', slug: 'bags' },
  },
  {
    id: '7',
    slug: 'wallet-pattern',
    title: 'Minimalist Wallet',
    description: 'Sleek bifold wallet with card slots and bill compartment.',
    long_description: 'Create a professional-looking wallet with this detailed pattern. Perfect for gifts or personal use. Includes instructions for card slots, bill compartment, and snap closure.',
    price: 10.99,
    cover_url: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800',
    preview_images: [],
    file_url: '/patterns/wallet.pdf',
    difficulty: 'intermediate' as const,
    category: 'accessories',
    tags: ['wallet', 'accessories', 'leather'],
    whats_included: [
      'Full-size pattern',
      'Card slot construction',
      'Snap installation guide',
      'Leather working tips',
    ],
    featured: false,
    bestseller: true,
    active: true,
    rating_avg: 4.8,
    rating_count: 67,
    sales_count: 445,
    created_at: '2024-02-20T00:00:00Z',
    updated_at: '2024-02-20T00:00:00Z',
    categories: { name: 'Accessories', slug: 'accessories' },
  },
  {
    id: '8',
    slug: 'tote-bag-with-pockets',
    title: 'Market Tote with Pockets',
    description: 'Spacious market tote with exterior and interior pockets.',
    long_description: 'This versatile market tote is perfect for shopping, beach trips, or everyday use. Features multiple pockets for organization, reinforced handles, and a flat bottom for stability.',
    price: 13.99,
    cover_url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800',
    preview_images: [],
    file_url: '/patterns/market-tote.pdf',
    difficulty: 'beginner' as const,
    category: 'bags',
    tags: ['tote', 'bag', 'market bag'],
    whats_included: [
      'Full-size pattern pieces',
      'Pocket placement guide',
      'Handle reinforcement tutorial',
      'Flat bottom construction',
    ],
    featured: false,
    bestseller: true,
    active: true,
    rating_avg: 4.7,
    rating_count: 134,
    sales_count: 789,
    created_at: '2024-01-30T00:00:00Z',
    updated_at: '2024-01-30T00:00:00Z',
    categories: { name: 'Bags', slug: 'bags' },
  },
  {
    id: '9',
    slug: 'drawstring-backpack',
    title: 'Drawstring Backpack',
    description: 'Easy drawstring backpack perfect for gym or day trips.',
    long_description: 'Simple yet functional drawstring backpack pattern. Great for beginners! Features adjustable straps, drawstring closure, and optional exterior pocket.',
    price: 11.99,
    cover_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800',
    preview_images: [],
    file_url: '/patterns/drawstring-backpack.pdf',
    difficulty: 'beginner' as const,
    category: 'bags',
    tags: ['backpack', 'drawstring', 'gym bag'],
    whats_included: [
      'Full-size pattern',
      'Drawstring channel tutorial',
      'Strap adjustment guide',
      'Optional pocket pattern',
    ],
    featured: true,
    bestseller: false,
    active: true,
    rating_avg: 4.6,
    rating_count: 98,
    sales_count: 512,
    created_at: '2024-02-05T00:00:00Z',
    updated_at: '2024-02-05T00:00:00Z',
    categories: { name: 'Bags', slug: 'bags' },
  },
]

export const mockBlogPosts = [
  {
    id: '1',
    slug: 'getting-started-with-sewing',
    title: 'Getting Started with Sewing: A Complete Beginner\'s Guide',
    excerpt: 'Everything you need to know to start your sewing journey, from choosing your first machine to completing your first project.',
    content: '<p>Welcome to the wonderful world of sewing! Whether you want to create your own clothes, make gifts for loved ones, or start a handmade business, this guide will help you get started.</p><h2>What You\'ll Need</h2><p>Starting with sewing doesn\'t require a huge investment. Here are the essentials...</p>',
    cover_url: 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=800',
    category: 'Tutorials',
    tags: ['beginner', 'getting started', 'basics'],
    published: true,
    featured: true,
    view_count: 1245,
    created_at: '2024-01-10T00:00:00Z',
    updated_at: '2024-01-10T00:00:00Z',
    published_at: '2024-01-10T00:00:00Z',
  },
  {
    id: '2',
    slug: 'choosing-the-right-fabric',
    title: 'How to Choose the Right Fabric for Your Project',
    excerpt: 'Learn about different fabric types and how to select the perfect material for your sewing projects.',
    content: '<p>Choosing the right fabric is crucial for the success of your sewing project. Different fabrics have different properties...</p>',
    cover_url: 'https://images.unsplash.com/photo-1558769132-cb1aea1f1f57?w=800',
    category: 'Tips',
    tags: ['fabric', 'materials', 'tips'],
    published: true,
    featured: false,
    view_count: 892,
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
    published_at: '2024-01-15T00:00:00Z',
  },
]

export const mockFreeResources = [
  {
    id: '1',
    title: 'Beginner\'s Sewing Glossary',
    description: 'A comprehensive guide to common sewing terms and techniques.',
    file_url: '/resources/sewing-glossary.pdf',
    thumbnail_url: 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=400',
    category: 'Beginner Guides',
    download_count: 2456,
    active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    title: 'Fabric Cutting Guide',
    description: 'Learn the best techniques for cutting fabric accurately and efficiently.',
    file_url: '/resources/cutting-guide.pdf',
    thumbnail_url: 'https://images.unsplash.com/photo-1558769132-cb1aea1f1f57?w=400',
    category: 'Tips & Tricks',
    download_count: 1823,
    active: true,
    created_at: '2024-01-05T00:00:00Z',
  },
]
